steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/sneha-creations/restapi:$COMMIT_SHA', '.']
# Push the image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/sneha-creations/restapi:$COMMIT_SHA']
# Deploy image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'restapi'
  - '--image'
  - 'gcr.io/sneha-creations/restapi:$COMMIT_SHA'
  - '--region'
  - 'us-west1'
  - '--platform'
  - 'managed'
images:
- gcr.io/sneha-creations/restapi
timeout: 1200s
