# Generated by Django 3.2.13 on 2022-07-02 07:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('7aa48bfb-ec54-4336-86fc-d3a989ec1b2e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
