# Generated by Django 3.2.13 on 2022-07-02 16:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220702_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timingtodo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('db861fa9-7843-40ab-95c7-6c24f8a81367'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('db861fa9-7843-40ab-95c7-6c24f8a81367'), editable=False, primary_key=True, serialize=False),
        ),
    ]
